// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA146JONM_lVWoD7mUB0P7ezOudpTeQ_Iw',
    appId: '1:424146220105:web:1f2b6d7c1a1609dac4fb98',
    messagingSenderId: '424146220105',
    projectId: 'tiktok-dg',
    authDomain: 'tiktok-dg.firebaseapp.com',
    storageBucket: 'tiktok-dg.appspot.com',
    measurementId: 'G-2R99MPQ5GY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYJl6bfzQ66h7jvGlTG58nWyNatSj5D7U',
    appId: '1:424146220105:android:d69987e009f39ddbc4fb98',
    messagingSenderId: '424146220105',
    projectId: 'tiktok-dg',
    storageBucket: 'tiktok-dg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3f9ih8tX6IDVuPJ6Pa9OGBWZ2Yp7O4ss',
    appId: '1:424146220105:ios:4ba74df1daeb894ec4fb98',
    messagingSenderId: '424146220105',
    projectId: 'tiktok-dg',
    storageBucket: 'tiktok-dg.appspot.com',
    iosClientId: '424146220105-6o3hrg51en3bg4jn973bror3ku135bjp.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3f9ih8tX6IDVuPJ6Pa9OGBWZ2Yp7O4ss',
    appId: '1:424146220105:ios:4ba74df1daeb894ec4fb98',
    messagingSenderId: '424146220105',
    projectId: 'tiktok-dg',
    storageBucket: 'tiktok-dg.appspot.com',
    iosClientId: '424146220105-6o3hrg51en3bg4jn973bror3ku135bjp.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
